name: Update Versions Manifest

on:
  workflow_dispatch:
  schedule:
    # Run every day at 1:00
    - cron: '0 1 * * *'

jobs:
  update:
    name: Update Versions Manifest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install requirements
      run: pip install requests
    - name: Generate Versions Manifest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python generate-versions-manifest.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        branch: update-versions-manifest
        delete-branch: true
        add-paths: |
          versions-manifest.json
        title: 'Update versions-manifest.json'
        commit-message: 'Update versions-manifest.json'
